---
title: "2nd moment test"
author: "Thea Dowrich"
date: "10/17/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages, include = FALSE}
library(tidyverse)
```

```{r data, include = FALSE}
turbtrain <- read.csv("data-train.csv")
```

```{r check-ranges}
hist(turbtrain$St)
hist(turbtrain$Re) #3 distinct groups
hist(turbtrain$Fr) #2 distinct groups (+ infinity)
```

```{r refactor}
turbtrain$Re <- as.factor(turbtrain$Re)
turbtrain$Fr <- as.factor(turbtrain$Fr)
```


```{r relationships}
par(mfrow = c(1, 3))
plot(turbtrain$St, turbtrain$R_moment_2)
plot(turbtrain$Re, turbtrain$R_moment_2)
plot(turbtrain$Fr, turbtrain$R_moment_2)
```
Most of the 2nd moment values for Re = 224 and Re = 398 are ~ 0, very small IQR (basically flat). Seeing similar results for `Fr`. 



```{r regular-lm}
baselm <- lm(R_moment_2 ~ St + Re + Fr, data = turbtrain)
summary(baselm)
```
p-value for St = 0.204 > 0.05, so potentially insignificant. Will run another lm without `St`.

```{r lm2}
lm2 <- lm(R_moment_2 ~ Re + Fr, data = turbtrain)
summary(lm2)
```

```{r}
lm3 <- lm(R_moment_2 ~ Re*Fr, data = turbtrain)
summary(lm3)
```
Tried with interaction terms and they do appear to be significant, so going to keep them in. But also Re398:Fr0.3 is returning NA, unclear why though. 














