---
title: "4th Moment Model"
author: "Matty Pahren"
date: "10/17/2020"
output: pdf_document
---

```{r}
library(tidyverse)
library(boot)
```


```{r Read In Data}
turbulence <- read.csv("data-train.csv")

turbulence$Sv = turbulence$St / turbulence$Fr

turbulence$Re_factor <- as.factor(turbulence$Re)
# original levels were 224  90 398
levels(turbulence$Re_factor) <- c("Low", "Med", "High")

```

```{r}
mod.moment4 <- lm(R_moment_4 ~ Re_factor + Sv + St, data=turbulence)
summary(mod.moment4)
plot(mod.moment4)
```

```{r}
mod.moment4_glm = glm(R_moment_4 ~ Re_factor + Sv + St, data=turbulence)
cv.glm(turbulence, mod.moment4_glm)$delta[1]
```


```{r}
m1 <- lm(log(R_moment_4) ~ Re_factor + Sv + St, data=turbulence)
summary(m1)
plot(m1)
```

```{r}
m1_glm = glm(log(R_moment_4) ~ Re_factor + Sv + St, data=turbulence)
cv.glm(turbulence, m1_glm)$delta[1]
```



```{r}
# best model
m2 <- lm(log(R_moment_4) ~ Re_factor + Sv + St + Re_factor*Sv + Re_factor*St + Sv*St, data=turbulence)
summary(m2)
plot(m2)
```

```{r}
m2_glm = glm(log(R_moment_4) ~ Re_factor + Sv + St + Re_factor*Sv + Re_factor*St + Sv*St, data=turbulence)
cv.glm(turbulence, m2_glm)$delta[1]
```

```{r}
turbulence$Sv_2 = turbulence$Sv^2
turbulence$St_2 = turbulence$St^2

m3 <- lm(log(R_moment_4) ~ Re_factor + Sv + Sv_2 + St + St_2 + Re_factor*Sv + Re_factor*St + Sv*St, data=turbulence)
summary(m3)
plot(m3)
```


```{r}
m3_glm = glm(log(R_moment_4) ~ Re_factor + Sv + Sv_2 + St + St_2 + Re_factor*Sv + Re_factor*St + Sv*St, data=turbulence)
cv.glm(turbulence, m3_glm)$delta[1]
```


